[build]
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[functions]
  directory = ".netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "false"